version: "3.8"

services:
  karmachari_frontend:
    container_name: karmachari_frontend
    build: 
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
      - NEXT_PUBLIC_API=${NEXT_PUBLIC_API}
    depends_on:
      - karmachari_backend
      # - mongo

  karmachari_backend:
    container_name: karmachari_backend
    build: 
      context: ./backend
      dockerfile: ../Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - FRONTEND_URL=${FRONTEND_URL}
    #   MONGO_URL: "mongodb://mongo:27017/mydb"
    #   MINIO_ENDPOINT: "minio:9000"
    #   MINIO_ACCESS_KEY: "myaccesskey"
    #   MINIO_SECRET_KEY: "mysecretkey"
    # depends_on:
    #   - mongo
    #   - minio

#   karmachari_db:
#     container_name: karmachari_db
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=root
#       - MONGO_INITDB_ROOT_PASSWORD=example
#       - MONGO_INITDB_DATABASE=mydb

#   karmachari_minio:
#     container_name: karmachari_minio
#     image: minio/minio:latest
#     ports:
#       - "9000:9000"
#     environment:
#       MINIO_ACCESS_KEY: "myaccesskey"
#       MINIO_SECRET_KEY: "mysecretkey"
#     volumes:
#       - minio-data:/data

# volumes:
#   mongo-data:
#   minio-data:
